title: Listd
default_lang: en
author:
  name: KalAbaddon
taxonomies:
  - category
  - tag
metadata:
  description: 'Listd is an online checklist for DCS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
