title: Listd
default_lang: en
author:
  name: KalAbaddon
  email: john@example.com
taxonomies:
  - category
  - tag
  - craft
  - author
  - type
metadata:
  description: 'Listd is an online checklist for DCS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
